Repository juryheed/EngNews, pull requests merged in 2024-11, with the labels that each got.

#4 Feature/#3 회원가입, 로그인, 로그아웃 구현
  build.gradle
  src/main/java/org/mjulikelion/engnews/authentication/AccessTokenProvider.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticatedUser.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticatedUserArgumentResolver.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticationContext.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticationExtractor.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticationInterceptor.java
  src/main/java/org/mjulikelion/engnews/authentication/JwtEncoder.java
  src/main/java/org/mjulikelion/engnews/authentication/PasswordHashEncryption.java
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/config/CorsConfig.java
  src/main/java/org/mjulikelion/engnews/controller/AuthController.java
  src/main/java/org/mjulikelion/engnews/dto/request/LoginDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/SignupDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/ResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/TokenResponseDto.java
  src/main/java/org/mjulikelion/engnews/entity/BaseEntity.java
  src/main/java/org/mjulikelion/engnews/entity/User.java
  src/main/java/org/mjulikelion/engnews/repository/UserRepository.java
  src/main/java/org/mjulikelion/engnews/service/AuthService.java
  src/main/java/org/mjulikelion/engnews/service/CookieService.java
  src/main/java/org/mjulikelion/engnews/service/UserService.java
Labels: enhancement

#6 Feature/#2 Exception 설정
  src/main/java/org/mjulikelion/engnews/exception/BadRequestException.java
  src/main/java/org/mjulikelion/engnews/exception/ConflictException.java
  src/main/java/org/mjulikelion/engnews/exception/CustomException.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/exception/ForbiddenException.java
  src/main/java/org/mjulikelion/engnews/exception/NotFoundException.java
  src/main/java/org/mjulikelion/engnews/exception/UnauthorizedException.java
  src/main/java/org/mjulikelion/engnews/exception/ValidationException.java
  src/main/java/org/mjulikelion/engnews/exception/controller/ExceptionController.java
  src/main/java/org/mjulikelion/engnews/exception/dto/ErrorResponseDto.java
  src/main/java/org/mjulikelion/engnews/response/ResponseDto.java
Labels: enhancement

#8 Feature/#7 에러 코드 추가
  src/main/java/org/mjulikelion/engnews/authentication/AccessTokenProvider.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticationExtractor.java
  src/main/java/org/mjulikelion/engnews/authentication/AuthenticationInterceptor.java
  src/main/java/org/mjulikelion/engnews/authentication/JwtEncoder.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/service/UserService.java
Labels: enhancement

#9 Feauret/#5 엔티티 생성
  src/main/java/org/mjulikelion/engnews/entity/ArticleLike.java
  src/main/java/org/mjulikelion/engnews/entity/BaseEntity.java
  src/main/java/org/mjulikelion/engnews/entity/Category.java
  src/main/java/org/mjulikelion/engnews/entity/Keyword.java
  src/main/java/org/mjulikelion/engnews/entity/User.java
  src/main/java/org/mjulikelion/engnews/entity/WordLike.java
  src/main/java/org/mjulikelion/engnews/entity/type/CategoryType.java
Labels: enhancement

#10 Create README
  README.md
Labels: enhancement

#12 Feature/#11 찜한 단어 기능 구현
  src/main/java/org/mjulikelion/engnews/EngNewsApplication.java
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/WordLikeController.java
  src/main/java/org/mjulikelion/engnews/dto/request/CreateWordLikeDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/WordLikeListResponseData.java
  src/main/java/org/mjulikelion/engnews/dto/response/WordLikeResponseDto.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/repository/WordLikeRepository.java
  src/main/java/org/mjulikelion/engnews/service/WordLikeService.java
Labels: enhancement

#14 Feature/#13 카테고리 기능 구현
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/AuthController.java
  src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
  src/main/java/org/mjulikelion/engnews/controller/WordLikeController.java
  src/main/java/org/mjulikelion/engnews/dto/request/category/CategoryListDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/user/LoginDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/user/SignupDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/wordLike/CreateWordLikeDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/NaverCategoryListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/UserCategoryListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/wordLike/WordLikeListResponseData.java
  src/main/java/org/mjulikelion/engnews/dto/response/wordLike/WordLikeResponseDto.java
  src/main/java/org/mjulikelion/engnews/repository/CategoryRepository.java
  src/main/java/org/mjulikelion/engnews/service/AuthService.java
  src/main/java/org/mjulikelion/engnews/service/CategoryService.java
  src/main/java/org/mjulikelion/engnews/service/WordLikeService.java
Labels: enhancement

#17 Feature/#16 누락된 파일 추가
  build.gradle
  src/main/java/org/mjulikelion/engnews/controller/AuthController.java
  src/main/java/org/mjulikelion/engnews/dto/request/auth/LoginDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/auth/SignupDto.java
  src/main/java/org/mjulikelion/engnews/dto/request/wordLike/CreateWordLikeDto.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/service/AuthService.java
Labels: enhancement

#18 Feature/#15 키워드 기능 구현
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/keywordController.java
  src/main/java/org/mjulikelion/engnews/dto/request/keyword/KeywordDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordsListResponseDto.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/repository/CategoryRepository.java
  src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
  src/main/java/org/mjulikelion/engnews/service/KeywordService.java
Labels: enhancement

#21 Feature/#20 찜한 뉴스 기능 구현
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/ArticleLikeController.java
  src/main/java/org/mjulikelion/engnews/dto/request/articleLike/ArticleLikeUrlDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/articleLike/ArticleLikeListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/articleLike/ArticleLikeResponseDto.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
Labels: enhancement

#26 Feature/#25 네이버 기사 카테고리 별 크롤링
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/dto/request/article/CategoryRequestDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/article/CategoryArticleDto.java
  src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#24 Feature/#22 마이페이지 기능 구현
  src/main/java/org/mjulikelion/engnews/controller/UserController.java
  src/main/java/org/mjulikelion/engnews/dto/response/user/MypageDto.java
  src/main/java/org/mjulikelion/engnews/service/UserService.java
Labels: enhancement

#31 Feature/#29 카테고리 기능 로직 수정
  src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryResponseDto.java
  src/main/java/org/mjulikelion/engnews/entity/Category.java
  src/main/java/org/mjulikelion/engnews/entity/type/CategoryType.java
  src/main/java/org/mjulikelion/engnews/service/CategoryService.java
Labels: enhancement

#36 Feature/#35 API 명세서에 맞도록 형식 변경
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
Labels: enhancement

#38 Feature/#37 CI/CD 설정
  .github/workflows/gradle.yml
Labels: enhancement

#40 Feature/#39 NYT 뉴스 기사 크롤링 기능 구현
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
Labels: enhancement

#46 Feature/#45 카테고리 별 기사 조회 페이지네이션
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#44 Feature/#42 키워드로 네이버 뉴스 크롤링하기 로직 변경
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#47 Feature/#43 카테고리 옵션 엔티티 추가
  src/main/java/org/mjulikelion/engnews/dto/request/category/CategoryListDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryListResponseDto.java
  src/main/java/org/mjulikelion/engnews/entity/Category.java
  src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
  src/main/java/org/mjulikelion/engnews/repository/CategoryOptionsRepository.java
  src/main/java/org/mjulikelion/engnews/service/CategoryService.java
Labels: enhancement

#48 Feature:#41 마이페이지 유저 정보 조회시 카테고리랑 키워드 같이 보내도록 수정
  src/main/java/org/mjulikelion/engnews/dto/response/user/MypageDto.java
  src/main/java/org/mjulikelion/engnews/service/UserService.java
Labels: enhancement

#52 Feature/#51 뉴스 별 카테고리 목록 조회
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
  src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
  src/main/java/org/mjulikelion/engnews/service/CategoryService.java
Labels: enhancement

#54 Feature/#53 top5 뉴스 불러오기
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#59 Feature/#57 AuthenticationConfig경로 수정
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
Labels: bug, enhancement

#60 Feature/#58 키워드 조회 로직 변경
  src/main/java/org/mjulikelion/engnews/controller/keywordController.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/CategoryKeywordListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/CategoryKeywordResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordResponseDto.java
  src/main/java/org/mjulikelion/engnews/service/KeywordService.java
Labels: enhancement

#61 Feature/#49 기사 요약,번역 기능 연결
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/SummarizeController.java
  src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/FeedbackDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/TryDto.java
  src/main/java/org/mjulikelion/engnews/service/SummarizeService.java
  src/main/java/org/mjulikelion/engnews/service/TranslateService.java
Labels: enhancement

#63 Feature/#62 네이버 뉴스 관련 기사 조회하기
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/dto/response/article/RelatedArticleDto.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#65 Feature/#64 키워드 조회 로직 변경
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/keywordController.java
  src/main/java/org/mjulikelion/engnews/dto/request/keyword/KeywordDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/CategoryKeywordResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionListResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordResponseDto.java
  src/main/java/org/mjulikelion/engnews/entity/Category.java
  src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
  src/main/java/org/mjulikelion/engnews/entity/Keyword.java
  src/main/java/org/mjulikelion/engnews/entity/KeywordOptions.java
  src/main/java/org/mjulikelion/engnews/entity/User.java
  src/main/java/org/mjulikelion/engnews/repository/CategoryOptionsRepository.java
  src/main/java/org/mjulikelion/engnews/repository/KeywordOptionsRepository.java
  src/main/java/org/mjulikelion/engnews/service/KeywordService.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#67 Feature/#66 로그인 유지 시간 변경
  src/main/java/org/mjulikelion/engnews/service/CookieService.java
Labels: enhancement

#73 Feature/#72 찜한 기사 뉴스 별 조회 로직 수정
  src/main/java/org/mjulikelion/engnews/controller/ArticleLikeController.java
  src/main/java/org/mjulikelion/engnews/dto/request/articleLike/ArticleLikeDto.java
  src/main/java/org/mjulikelion/engnews/entity/ArticleLike.java
  src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
Labels: enhancement

#75 Feature/#74 기사 정렬 기능 추가
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#77 Hotfix/#76 Build 오류 해결
  src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
Labels: bug
