Repository juryheed/EngNews, pull requests merged in 2024-12, with the labels that each got.

#83 Feature/#78 ML /영어 → 한글로 통번역 AI 연결
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/E2kResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/E2kTranslateDto.java
  src/main/java/org/mjulikelion/engnews/service/TranslateService.java
Labels: enhancement

#84 Feature/#79 ML translate API연결
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/TranslateDto.java
  src/main/java/org/mjulikelion/engnews/service/TranslateService.java
Labels: enhancement

#85 Feature/#80 ML /한글 → 영어로 통번역 AI 연결
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/K2eResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/K2eTranslateDto.java
  src/main/java/org/mjulikelion/engnews/service/TranslateService.java
Labels: enhancement

#86 Feature/#81 ML /analyze-sentence API연결
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/AnalyzeController.java
  src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/AnalyzeSentenceDto.java
  src/main/java/org/mjulikelion/engnews/service/AnalyzeService.java
  src/main/java/org/mjulikelion/engnews/service/TranslateService.java
Labels: enhancement

#88 Feature/#82 ML /try-translate API연결 로직 수정
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/ai/AnalyzeController.java
  src/main/java/org/mjulikelion/engnews/controller/ai/SummarizeController.java
  src/main/java/org/mjulikelion/engnews/controller/ai/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/AnalyzeSentenceDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/E2kTranslateDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/K2eTranslateDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TranslateDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TrySummarizeDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TryTranslateDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/response/E2kResponseDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/response/FeedbackDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/response/K2eResponseDto.java
  src/main/java/org/mjulikelion/engnews/service/ai/AnalyzeService.java
  src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
  src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
Labels: enhancement

#90 Feature/#87 키워드 로직 수정
  src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
  src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryInfoDto.java
  src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionDto.java
  src/main/java/org/mjulikelion/engnews/service/CategoryService.java
Labels: enhancement

#91 Feature/#89 기사 단건 조회시 articleId반환하도록 수정
  src/main/java/org/mjulikelion/engnews/controller/ArticleLikeController.java
  src/main/java/org/mjulikelion/engnews/dto/response/articleLike/ArticleLikeResponseDto.java
  src/main/java/org/mjulikelion/engnews/entity/ArticleLike.java
  src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#93 Feature/#92 관련 기사 오류 수정
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
Labels: enhancement

#95 Refactor/#94 코드 리팩터링
  src/main/java/org/mjulikelion/engnews/controller/KeywordController.java
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
  src/main/java/org/mjulikelion/engnews/service/KeywordService.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
  src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
  src/main/java/org/mjulikelion/engnews/service/WordLikeService.java
Labels: refactor

#97 Bug/#96 getNYTByCategory 서비스 로직 변경
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
Labels: bug

#99 Bug/#98 getNYTByCategory 서비스 로직 변경
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
Labels: bug

#101 Hotfix/#100 키워드 삭제 로직 수정
  src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
  src/main/java/org/mjulikelion/engnews/service/KeywordService.java
Labels: bug, enhancement

#103 Feature/#102 NYT 단건 기사 조회 로직 수정
  src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
  src/main/java/org/mjulikelion/engnews/dto/response/article/ArticleNytDto.java
  src/main/java/org/mjulikelion/engnews/response/ArticleResponse.java
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
Labels: enhancement

#105 Feature/#104 ML주소 변경 반영
  src/main/java/org/mjulikelion/engnews/service/ai/AnalyzeService.java
  src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
  src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
Labels: enhancement

#110 Feature/#106 번역/요약 요청 분리
  src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
  src/main/java/org/mjulikelion/engnews/controller/ai/SummarizeController.java
  src/main/java/org/mjulikelion/engnews/controller/ai/TranslateController.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TrySummarizeContentDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TrySummarizeMessageDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TryTranslateMessageDto.java
  src/main/java/org/mjulikelion/engnews/dto/ai/request/TryTranslateSentenceDto.java
  src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
  src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
Labels: enhancement

#111 Refactor/#109 응답 메세지 처리 수정
  src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
Labels: refactor

#113 Refactor/#112 응답 메세지 처리 수정2
  src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
Labels: refactor

#117 Feature/#116 nyt 기본 이미지 변경
  src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
Labels: enhancement, refactor

#119 Hotfix/#118 nyt 뉴스 조회 오류 해결
  src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
Labels: bug, enhancement
